# Generated by Django 2.2 on 2020-03-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meublog', '0002_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
